name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v2

      - name: Nastavení Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Instalace závislostí
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements-test.txt

      - name: Spuštění testů
        run: pytest tests

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v2

      - name: Nasazení na server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/chat
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            systemctl restart muj_python_server