name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v2

      - name: Nastavení Pythonu
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.12'

      - name: Instalace závislostí
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Nastavení Google credentials
        run: echo '${{ secrets.GOOGLE_CREDENTIALS_JSON }}' > google-credentials.json

      - name: Spuštění testů
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)
          pytest tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          GOOGLE_APPLICATION_CREDENTIALS: google-credentials.json

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout kódu
        uses: actions/checkout@v2
      - name: Přidání host key serveru do known_hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_KNOWN_HOSTS }}" > ~/.ssh/known_hosts
      - name: Přidání SSH klíče
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
      - name: Připojení k serveru a nasazení
        run: |
          ssh -o StrictHostKeyChecking=yes -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} <<EOF
          set -e # Ukončí skript hned při chybě
          rm -rf ~/chat
          git clone git@github.com:Kubis1414/e-commerce-chatbot.git ~/chat
          cd ~/chat
          echo "${{ secrets.ENV_VARS }}" > .env
          git pull
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install -r requirements.txt
          systemctl restart ecommerce_chatbot.service
          systemctl status ecommerce_chatbot.service
          EOF